### ISSUE TITLE
Error when while running/reading

### ISSUE THREAD

**Issue by finfin82** [kbialek/deye-inverter-mqtt#1]
Hi There im a big fan of Deye too and im looking for a way to monitor the data.
this project seems to be very auspicious.

I tried to run the project with 
docker run --rm --env-file config.env ghcr.io/kbialek/deye-inverter-mqtt

and got the following output.
Any Idea what could be the problem?
Thanks very much!
finfin

2022-10-07 18:01:49,126 - DeyeDaemon - INFO - Reading start
Traceback (most recent call last):
  File "/opt/deye_inverter_mqtt/./deye_docker_entrypoint.py", line 43, in <module>
    main()
  File "/opt/deye_inverter_mqtt/./deye_docker_entrypoint.py", line 39, in main
    daemon_main()
  File "/opt/deye_inverter_mqtt/deye_daemon.py", line 61, in main
    daemon.do_task()
  File "/opt/deye_inverter_mqtt/deye_daemon.py", line 42, in do_task
    regs = self.modbus.read_registers(0x3c, 0x4f) \
TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'

**Comment by kbialek** [comment]
hi @finfin82 
I've fixed the error. New images are pushed. Thanks for reporting it.
Yet, it has appeared for you, because the service could not read registers from your inverter.
