### ISSUE TITLE
Error with Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by JensHoRi** [kbialek/deye-inverter-mqtt#202]
after update I got failures
`2024-09-29T14:57:35.180688+02:00 alderaan deye-inverter-600[185156]: Traceback (most recent call last):
2024-09-29T14:57:35.180786+02:00 alderaan deye-inverter-600[185156]:   File "/usr/local/share/deye-inverter-mqtt/deye_docker_entrypoint.py", line 21, in <module>
2024-09-29T14:57:35.180837+02:00 alderaan deye-inverter-600[185156]:     from deye_cli import main as cli_main
2024-09-29T14:57:35.180870+02:00 alderaan deye-inverter-600[185156]:   File "/usr/local/share/deye-inverter-mqtt/deye_cli.py", line 22, in <module>
2024-09-29T14:57:35.180899+02:00 alderaan deye-inverter-600[185156]:     from deye_modbus import DeyeModbus
2024-09-29T14:57:35.180927+02:00 alderaan deye-inverter-600[185156]:   File "/usr/local/share/deye-inverter-mqtt/deye_modbus.py", line 20, in <module>
2024-09-29T14:57:35.180958+02:00 alderaan deye-inverter-600[185156]:     import libscrc
2024-09-29T14:57:35.180987+02:00 alderaan deye-inverter-600[185156]: ModuleNotFoundError: No module named 'libscrc' `

I believe reason is python 3.12 seems not containing libscrc anymore?

**Comment by JensHoRi** [comment]
python3.12 -m pip install libscrc --break-system-packages

Did it
